// src/components/sections/HeroSection.tsx
import { component$ } from "@builder.io/qwik";
import type { ClassList } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import {
	FaUpRightFromSquareSolid,
} from "@qwikest/icons/font-awesome";
import { SiGithub, SiInstagram, SiLinkedin } from "@qwikest/icons/simpleicons";
import SvgLogo from "~/media/logo.svg?jsx";

export interface HeroProps {
	class?: ClassList;
}

/**
 * HeroSection component renders a hero section with a logo, heading, subtitle, and social links.
 *
 * @param {HeroProps} props - Component props.
 * @returns {JSX.Element} The hero section element.
 */
export const HeroSection = component$((props: HeroProps) => {
	return (
		<section class={["flex flex-col items-center justify-center", props.class]}>
			<SvgLogo width={96} height={96} />
			<h2 class="mt-8 text-center text-5xl font-bold">Fernando Sibarani</h2>
			<p class="mt-4 text-center text-3xl text-black-400">Software Engineer</p>
			<div class="mt-12 flex flex-wrap justify-center gap-x-8 gap-y-4 font-bold text-lg">
				<Link
					key="linkedin"
					href="https://linkedin.com/in/martuafernando"
					class="flex items-center text-[#0a66c2]"
					target="_blank"
					rel="noopener noreferrer"
				>
					<SiLinkedin height={48} class="h-8 w-auto" />
					<span class="flex items-center ml-2 gap-1 hover-underline-animation">
						LinkedIn <FaUpRightFromSquareSolid height={12} />
					</span>
				</Link>
				<Link
					href="https://github.com/martuafernando"
					class="flex items-center text-[#181717]"
					target="_blank"
					rel="noopener noreferrer"
				>
					<SiGithub height={48} class="h-8 w-auto" />
					<span class="flex items-center ml-2 gap-1 hover-underline-animation">
						GitHub <FaUpRightFromSquareSolid height={12} />
					</span>
				</Link>
				<Link
					href="https://instagram.com/martuafernando"
					class="flex items-center text-[#FF0069]"
					target="_blank"
					rel="noopener noreferrer"
				>
					<SiInstagram height={48} class="h-8 w-auto" />
					<span class="flex items-center ml-2 gap-1 hover-underline-animation">
						Instagram <FaUpRightFromSquareSolid height={12} />
					</span>
				</Link>
			</div>
		</section>
	);
});

// src/lib/sections/hero-section.svelte
<script>
  export let className = "";

  const socialLinks = [
    {
      name: "LinkedIn",
      url: "https://linkedin.com/in/martuafernando",
      icon: "icon-[fa6-brands--linkedin]",
    },
    {
      name: "GitHub",
      url: "https://github.com/martuafernando",
      icon: "icon-[fa6-brands--github]",
    },
    {
      name: "Instagram",
      url: "https://instagram.com/martuafernando",
      icon: "icon-[fa6-brands--instagram]",
    },
  ];
</script>

<section class={`flex flex-col items-center justify-center${className}`}>
  <!-- Logo Image -->
  <img class="mx-auto" src="/logos/logo.svg" alt="Logo" width="96" height="96" />

  <!-- Name & Title -->
  <h2 class="mt-8 text-center text-5xl font-bold">Fernando Sibarani</h2>
  <p class="mt-4 text-center text-3xl text-black-400">Software Engineer</p>

  <!-- Social Links -->
  <div class="mt-12 flex flex-wrap justify-center gap-x-8 gap-y-4 font-bold text-lg ">
    {#each socialLinks as { name, url, icon }}
      <a href={url} class="flex items-center" target="_blank" rel="noopener noreferrer">
        <span class={`${icon} text-3xl`}></span>
        <span class="flex items-center ml-2 gap-1 hover-underline-black-animation">
          {name} <span class="icon-[lets-icons--external] text-sm"></span>
        </span>
      </a>
    {/each}
  </div>
</section>
