// src/routes/projects/index.tsx
import { component$ } from "@builder.io/qwik";
import { ProjectList } from "~/components/ui/ProjectList";
import { getAllProject } from "~/repositories/project";

export default component$(() => {
	const projects = getAllProject();

	return (
		<>
			<h1 class="text-5xl font-bold text-center mt-8">Projects</h1>
			<ProjectList
				projects={projects}
				class="mx-auto mt-12 mb-8"
			/>
		</>
	);
});

// src/app/projects/page.tsx
import { getAllProjects } from "@/data/repositories/projects-repository";
import ProjectList from "@/presentation/components/project-list";

export const metadata = {
  title: "Projects",
  description: "Projects created by Martua Fernando",
};

export default function ProjectsPage() {
  const projects = [
    ...getAllProjects(),
  ];

  return (
    <>
      <h1 className="text-5xl font-bold text-center">Projects</h1>
      <div className="mt-8">
        <ProjectList projects={projects} />
      </div>
    </>
  );
}
