// src/routes/experiences/index.tsx
import { component$ } from "@builder.io/qwik";
import { ExperienceList } from "~/components/ui/ExperienceList";
import { getAllExperiences } from "~/repositories/experience";

export default component$(() => {
	const experiences = getAllExperiences();
	return (
		<>
			<h1 class="text-5xl font-bold text-center">Experience</h1>
			<div class="mt-8">
				<ExperienceList experiences={experiences} />
			</div>
		</>
	);
});

// src/routes/experiences/+page.svelte
<script>
	import ExperienceList from '$lib/components/Experience-List.svelte';

	export let data;
</script>

<svelte:head>
	<title>Home</title>
	<meta name="description" content="Learn to do the thing" />
</svelte:head>

<section class="mt-4 py-8 px-4 max-w-3xl mx-auto">
	<h2 class="text-5xl font-bold text-center">Experience</h2>
	<div class="mt-8">
		<ExperienceList experience={data.experiences} />
	</div>
</section>
