// src/lib/components/Footer.svelte
<script lang="ts">
  export const className: string = '';

  const socialLinks = [
    { href: "https://linkedin.com/in/martuafernando", label: "LinkedIn" },
    { href: "https://github.com/martuafernando", label: "GitHub" },
    { href: "https://instagram.com/martuafernando", label: "Instagram" }
  ];
</script>

<footer class="bg-black text-white py-16 rounded-t-4xl {className}">
  <a href="/" class="block mx-auto w-fit">
    <img src="/logos/logo-white.svg" alt="Logo" width="64" height="64" />
  </a>

  <div class="my-12 flex flex-col items-center">
    <h2 class="text-2xl font-bold mb-4 text-mint-500">Let's work together</h2>
    <a href="mailto:fernandosibarani45@gmail.com" class="flex items-center outline-1 mt-4 p-4 rounded-lg bg-black text-white">
      <span class="icon-[mdi--envelope] text-4xl"></span>
      <span class="flex items-center ml-2 gap-1 hover:underline">
        Email Me <span class="icon-[lets-icons--external]"></span>
      </span>
    </a>
  </div>

  <div class="flex flex-wrap justify-center gap-x-8 gap-y-2 w-fit mx-auto mt-8 text-xl">
    {#each socialLinks as link}
      <a
        href={link.href}
        target="_blank"
        rel="noopener noreferrer"
        class="relative font-bold after:content-[''] after:absolute after:w-full after:h-[1px] after:bg-white after:left-0 after:bottom-[-2px] after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:origin-left after:hover:origin-left after:duration-300"
      >
        <span>{link.label}</span>
        <span class="icon-[lets-icons--external] text-lg"></span>
      </a>
    {/each}
  </div>

  <p class="text-center mt-8">&copy; 2024 Martua Fernando</p>
</footer>

// src/presentation/components/footer-component.tsx
import Image from "next/image";
import Link from "next/link";
import { FiExternalLink } from "react-icons/fi";
import CallToActionComponent from "./call-to-action-component";
import { FaEnvelope } from "react-icons/fa";

export interface FooterProps {
  className?: string
}

export default function Footer(props: Readonly<FooterProps>) {
  const { className } = props

  return (
    <footer className={`bg-black text-white py-16 ${className}`}>
      <Image
        src="/logo-white.svg"
        className="text-white mx-auto"
        alt="Logo"
        width={64}
        height={64}
      />
      <CallToActionComponent
        className="my-12"
        isVertical
        title="Let's work together"
        links={[
          <Link
            key="email"
            href="mailto:mailto:fernandosibarani45@gmail.com"
            className="flex items-center outline outline-1 p-4 rounded-lg bg-black text-white"
          >
            <FaEnvelope size={24} />
            <span className="flex items-center ml-2 gap-1 hover-underline-animation after:bg-white">
              Email Me <FiExternalLink size={16} />
            </span>
          </Link>,
        ]}
      />
      <div className="flex flex-wrap justify-center gap-x-8 gap-y-2 w-fit mx-auto mt-8 text-xl">
        <Link
          href="https://linkedin.com/in/martuafernando"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center relative after:content-[''] after:absolute after:w-full after:h-[1px] after:bg-white after:left-0 after:bottom-[-2px] after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:origin-right after:hover:origin-left after:duration-300"
        >
          <span>LinkedIn</span>
          <FiExternalLink size={16} className="ml-2" />
        </Link>
        <Link
          href="https://github.com/martuafernando"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center relative after:content-[''] after:absolute after:w-full after:h-[1px] after:bg-white after:left-0 after:bottom-[-2px] after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:origin-right after:hover:origin-left after:duration-300"
        >
          <span>GitHub</span>
          <FiExternalLink size={16} className="ml-2" />
        </Link>
        <Link
          href="https://instagram.com/martuafernando"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center relative after:content-[''] after:absolute after:w-full after:h-[1px] after:bg-white after:left-0 after:bottom-[-2px] after:scale-x-0 hover:after:scale-x-100 after:transition-transform after:origin-right after:hover:origin-left after:duration-300"
        >
          Instagram
          <FiExternalLink size={16} className="ml-2" />
        </Link>
      </div>
      <p className="text-center mt-8">&copy; 2024 Martua Fernando</p>
    </footer>
  );
}
