// src/components/ui/Select.tsx
import {
	type ClassList,
	component$,
	type Signal,
} from "@builder.io/qwik";
import { Select as SelectUi } from "@qwik-ui/headless";
import { LuCheck, LuChevronDown } from "@qwikest/icons/lucide";

export type TPlacement = 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';

export interface SelectItem {
	label: string;
	value: string;
}

export interface SelectProps {
	class?: ClassList;
	items: Array<SelectItem> | string[];
	"bind:value"?: Signal<string>;
	value?: string;
	placeholder?: string;
	floating?: TPlacement;
}

export const Select = component$((props: SelectProps) => {
	return (
		<SelectUi.Root
			class={["bg-white rounded-xl select", props.class]}
			bind:value={props["bind:value"]}
			value={props.value}
		>
			<SelectUi.Trigger class="min-h-[44px] flex justify-center items-center mt-0.5 py-1 px-4 cursor-pointer font-medium">
				<SelectUi.DisplayValue placeholder={props.placeholder} />
				<LuChevronDown class="h-4 w-4 opacity-50 mt-0.5" />
			</SelectUi.Trigger>
			<SelectUi.Popover class="w-fit !py-2 !px-1 rounded-xl shadow-2xl" floating={props.floating} gutter={8}>
				{props.items.map((item) => {
					const value = typeof item === "string" ? item : item.value;
					const label = typeof item === "string" ? item : item.label;

					return (
						<SelectUi.Item class="flex justify-between items-center gap-8 px-4 py-2 cursor-pointer rounded-md hover:bg-gray-200" key={value} value={value}>
							<SelectUi.ItemLabel>{label}</SelectUi.ItemLabel>
							<SelectUi.ItemIndicator>
								<LuCheck />
							</SelectUi.ItemIndicator>
						</SelectUi.Item>
					);
				})}
			</SelectUi.Popover>
		</SelectUi.Root>
	);
});

// src/presentation/components/select-component.tsx
import React, { useState } from "react";
import { FaCheck, FaChevronDown } from "react-icons/fa6";

interface SelectComponentProps {
  items: Array<any>;
  className?: string;
  onChange?: Function;
}

export default function SelectComponent(props: Readonly<SelectComponentProps>) {
  const { items, onChange, className } = props;
  const [selected, setSelected] = useState(items[0]);
  const [isOpen, setIsOpen] = useState(false);

  function changeSelectedValue(selectedItem: any) {
    setSelected(selectedItem)
    if (onChange) {
      onChange(new CustomEvent('change', {
        detail: {
          value: selectedItem
        }
      }))
    }
  }

  return (
    <>
      <button className={`absolute cursor-default top-0 left-0 w-screen h-screen ${isOpen ? 'block' : 'hidden'}`} onClick={() => setIsOpen(false)} ></button>
      <div className={`relative w-fit ${className}`}>
        <button
          className="flex items-center gap-4 px-4 py-2 border border-gray-300 rounded-lg shadow-sm text-gray-700 text-left focus:ring-2 focus:ring-blue-500 focus:border-blue-500 hover:bg-gray-50 hover:shadow-md cursor-pointer"
          onClick={() => setIsOpen(!isOpen)}
        >
          <p className="w-full">{selected}</p>
          <FaChevronDown
            className={`${
              isOpen ? "rotate-180" : "rotate-0"
            } transition-transform duration-300 will-change-transform`}
          />
        </button>

        {isOpen && (
          <div className="absolute mt-2 px-2 py-4 w-max bg-white border border-gray-200 rounded-lg shadow-lg z-10">
            {items.map((item) => (
              <button
                key={item}
                onClick={() => {
                  changeSelectedValue(item);
                  setIsOpen(false);
                }}
                className={`flex gap-8 items-center justify-between w-full text-start px-4 py-2 text-gray-700 hover:bg-blue-100 cursor-pointer rounded-lg ${
                  item === selected ? "bg-blue-50" : ""
                }`}
              >
                {item}
                {item === selected && <FaCheck />}
              </button>
            ))}
          </div>
        )}
      </div>
    </>
  );
}
