// src/presentation/components/experience-list.tsx
import Experience from "@/domain/entities/experience";
import ExperienceItem from "./experience-item";

export default function ExperienceList({
  experience,
  className,
}: {
  readonly className?: string;
  readonly experience: Experience[];
}) {
  return (
    <div className={className}>
      {experience.map((experience) => (
        <ExperienceItem
          key={experience.companyName}
          experience={experience}
          className="border-t first:border-none py-8"
        />
      ))}
    </div>
  );
}

// src/lib/components/Experience-List.svelte
<script lang="ts">
	import type Experience from "$lib/models/Experience";
	import ExperienceItem from "./Experience-Item.svelte";

  export let experience: Experience[] = [];
  export let className = "";
</script>

<div class={className}>
  {#each experience as exp}
    <ExperienceItem 
      experience={exp}
      className="border-t first:border-none py-8"
    />
  {/each}
</div>
