// src/presentation/components/experience-list.tsx
import Experience from "@/domain/entities/experience";
import ExperienceItem from "./experience-item";

export default function ExperienceList({
  experience,
  className,
}: {
  readonly className?: string;
  readonly experience: Experience[];
}) {
  return (
    <div className={className}>
      {experience.map((experience) => (
        <ExperienceItem
          key={experience.companyName}
          experience={experience}
          className="border-t first:border-none py-8"
        />
      ))}
    </div>
  );
}

// src/components/ui/ExperienceList.tsx
import { type ClassList, component$ } from "@builder.io/qwik";
import { ExperienceItem } from "./ExperienceItem";
import type Experience from "~/domains/Experience";

export interface ExperienceListProps {
	class?: ClassList;
	experiences: Array<Experience>;
}

export const ExperienceList = component$((props: ExperienceListProps) => {
	const experiences = props.experiences

	return (
		<div class={props.class}>
			{experiences.map((experience) => (
				<ExperienceItem
					key={experience.companyName}
					experience={experience}
					class="border-t first:border-none py-8"
				/>
			))}
		</div>
	);
});
