// src/presentation/components/project-list.tsx
"use client";

import React, { useState } from "react";
import ProjectThumbnail from "@/presentation/components/project-thumbnail";
import Project from "@/domain/entities/project";
import SelectComponent from "./select-component";
import useWindowSize from "../hook/useWindowSize";
import { breakpoint } from "../constant/breakpoint";

interface ProjectListProps {
  projects: Project[];
  className?: string;
}

export default function ProjectList(props: Readonly<ProjectListProps>) {
  const { projects, className } = props;
  const [activeCategory, setActiveCategory] = useState("All");
  const [activeFilterTools, setActiveFilterTools] = useState("All Technology");
  const window = useWindowSize();

  const categoryList = [
    "All",
    ...projects
      .map((it) => it.category)
      .filter((value, index, array) => array.indexOf(value) === index),
  ];

  const toolsFilterOptions = [
    "All Technology",
    ...projects.flatMap((it) => it.tools.map((it) => it)),
  ];

  function onOrderFilterChage(event: CustomEvent) {
    setActiveFilterTools(event.detail.value);
  }

  return (
    <div className={`mx-auto max-w-screen-2xl w-[95vw] ${className ?? ""}`}>
      <div className="flex justify-between items-center">
        <div className="flex gap-4 overflow-auto whitespace-nowrap py-6">
          {categoryList.map((category) => (
            <ButtonChip
              key={category}
              label={category}
              isActive={activeCategory === category}
              onClick={() => setActiveCategory(category)}
            />
          ))}
        </div>
        {window.width >= breakpoint.sm && (
          <SelectComponent
            items={toolsFilterOptions}
            onChange={onOrderFilterChage}
          />
        )}
      </div>
      <hr className="block container mx-auto" />

      {window.width < breakpoint.sm && (
          <SelectComponent
            className="mt-6"
            items={toolsFilterOptions}
            onChange={onOrderFilterChage}
          />
        )}

      <div
        className={
          "mt-8 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-12 gap-y-4"
        }
      >
        {projects
          .filter(
            (project) =>
              (activeCategory === "All" ||
                project.category === activeCategory) &&
              (activeFilterTools === "All Technology" ||
                project.tools.some((it) => it === activeFilterTools))
          )
          .map((project) => (
            <ProjectThumbnail
              key={project.id}
              project={project}
              href={`/projects/${project.id}`}
            />
          ))}
      </div>
    </div>
  );
}

interface ButtonChipProps {
  label: string;
  onClick: () => void;
  className?: string;
  isActive: boolean;
}

function ButtonChip({
  label,
  onClick,
  className,
  isActive,
}: Readonly<ButtonChipProps>) {
  return (
    <button
      className={`font-medium px-4 py-2 rounded-full transition-all duration-300 ${
        isActive ? "bg-gray-200" : "bg-transparent"
      } ${className ?? ""}`}
      onClick={onClick}
    >
      {label}
    </button>
  );
}

// src/components/ui/ProjectList.tsx
import { type ClassList, component$, useSignal } from "@builder.io/qwik";
import { ProjectItem } from "./ProjectItem";
import type Project from "~/domains/Project";
import { ToggleGroup } from "./ToggleGroup";
import { Select } from "./Select";

export interface ProjectListProps {
	class?: ClassList;
	projects: Array<Project>;
}

export const ProjectList = component$((props: ProjectListProps) => {
	const projects = props.projects;

	const categoryList = [
		"All",
		...[...new Set(projects.map((it) => it.category))],
	];
	const activeCategory = useSignal<string>(categoryList[0]);

	const toolsFilterOptions = [
		"All Technology",
		...[...new Set(projects.flatMap((it) => it.tools))],
	];

	return (
		<div class={props.class}>
			<div class="flex flex-wrap gap-y-4 items-center justify-between">
				<Select items={toolsFilterOptions} />
				<div class="flex gap-2 overflow-auto whitespace-nowrap py-4">
					<ToggleGroup items={categoryList} bind:value={activeCategory} />
				</div>
			</div>

			<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-x-12 gap-y-12 mt-6">
				{props.projects
					.filter(
						(project) =>
							activeCategory.value === categoryList[0] ||
							project.category === activeCategory.value,
					)
					.map((project) => (
						<ProjectItem
							key={project.id}
							project={project}
							href={`/projects/${project.id}`}
						/>
					))}
			</div>
		</div>
	);
});

export const ProjectListSkeleton = component$(() => {
	return (
		<div class="animate-pulse">
			<hr class="container h-1 text-gray-200 mt-4" />
			<div class="flex gap-2 overflow-auto whitespace-nowrap mt-4">
				<div class="bg-gray-200 rounded-full h-8 w-16" />
				<div class="bg-gray-200 rounded-full h-8 w-16" />
				<div class="bg-gray-200 rounded-full h-8 w-16" />
			</div>

			<div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-x-12 gap-y-8 mt-6 mx-4">
				<div class="h-72 bg-gray-200 rounded " />
				<div class="h-72 bg-gray-200 rounded " />
				<div class="h-72 bg-gray-200 rounded " />
				<div class="h-72 bg-gray-200 rounded " />
				<div class="h-72 bg-gray-200 rounded " />
				<div class="h-72 bg-gray-200 rounded " />
			</div>
		</div>
	);
});
